INSERT INTO DEVICES VALUES(1, 'Czajnik');
INSERT INTO VARIABLES VALUES(1, 'Temperatura wody', 1);
INSERT INTO DEVICES VALUES(2, 'Grzejnik');
INSERT INTO VARIABLES VALUES(2, 'Temperatura grzejnika', 2);
